daemonize: false
debug: true
logfile: /var/log/pmacct/pmbgpd.log

bgp_daemon: true
bgp_daemon_ip: _LOCAL_IP_
bgp_daemon_as: _LOCAL_AS_
bgp_daemon_id: _LOCAL_IP_
bgp_daemon_port: 179
bgp_daemon_max_peers: 5

bgp_table_dump_file: /var/spool/pmacct/bgp-table-$peer_src_ip-%Y%m%d%H%M%S.json
bgp_table_dump_output: json
bgp_table_dump_refresh_time: 300
